/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FileFileIdRouteImport } from './routes/file.$fileId'
import { Route as AuthedToolsRouteImport } from './routes/_authed.tools'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedFolderFolderIdRouteImport } from './routes/_authed.folder.$folderId'
import { Route as AuthedFolderFolderIdFileFileIdModalRouteImport } from './routes/_authed.folder.$folderId.file.$fileId.modal'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileFileIdRoute = FileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedToolsRoute = AuthedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFolderFolderIdRoute = AuthedFolderFolderIdRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFolderFolderIdFileFileIdModalRoute =
  AuthedFolderFolderIdFileFileIdModalRouteImport.update({
    id: '/file/$fileId/modal',
    path: '/file/$fileId/modal',
    getParentRoute: () => AuthedFolderFolderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/tools': typeof AuthedToolsRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/folder/$folderId': typeof AuthedFolderFolderIdRouteWithChildren
  '/folder/$folderId/file/$fileId/modal': typeof AuthedFolderFolderIdFileFileIdModalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthedAdminRoute
  '/profile': typeof AuthedProfileRoute
  '/tools': typeof AuthedToolsRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/folder/$folderId': typeof AuthedFolderFolderIdRouteWithChildren
  '/folder/$folderId/file/$fileId/modal': typeof AuthedFolderFolderIdFileFileIdModalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/tools': typeof AuthedToolsRoute
  '/file/$fileId': typeof FileFileIdRoute
  '/_authed/folder/$folderId': typeof AuthedFolderFolderIdRouteWithChildren
  '/_authed/folder/$folderId/file/$fileId/modal': typeof AuthedFolderFolderIdFileFileIdModalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/profile'
    | '/tools'
    | '/file/$fileId'
    | '/folder/$folderId'
    | '/folder/$folderId/file/$fileId/modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/profile'
    | '/tools'
    | '/file/$fileId'
    | '/folder/$folderId'
    | '/folder/$folderId/file/$fileId/modal'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/admin'
    | '/_authed/profile'
    | '/_authed/tools'
    | '/file/$fileId'
    | '/_authed/folder/$folderId'
    | '/_authed/folder/$folderId/file/$fileId/modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  FileFileIdRoute: typeof FileFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$fileId': {
      id: '/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/file/$fileId'
      preLoaderRoute: typeof FileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tools': {
      id: '/_authed/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthedToolsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/folder/$folderId': {
      id: '/_authed/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof AuthedFolderFolderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/folder/$folderId/file/$fileId/modal': {
      id: '/_authed/folder/$folderId/file/$fileId/modal'
      path: '/file/$fileId/modal'
      fullPath: '/folder/$folderId/file/$fileId/modal'
      preLoaderRoute: typeof AuthedFolderFolderIdFileFileIdModalRouteImport
      parentRoute: typeof AuthedFolderFolderIdRoute
    }
  }
}

interface AuthedFolderFolderIdRouteChildren {
  AuthedFolderFolderIdFileFileIdModalRoute: typeof AuthedFolderFolderIdFileFileIdModalRoute
}

const AuthedFolderFolderIdRouteChildren: AuthedFolderFolderIdRouteChildren = {
  AuthedFolderFolderIdFileFileIdModalRoute:
    AuthedFolderFolderIdFileFileIdModalRoute,
}

const AuthedFolderFolderIdRouteWithChildren =
  AuthedFolderFolderIdRoute._addFileChildren(AuthedFolderFolderIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedToolsRoute: typeof AuthedToolsRoute
  AuthedFolderFolderIdRoute: typeof AuthedFolderFolderIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedToolsRoute: AuthedToolsRoute,
  AuthedFolderFolderIdRoute: AuthedFolderFolderIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  FileFileIdRoute: FileFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
